/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package budget_of_polytechnic;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Muhaimenur
 */
public class Non_govt_purchase extends javax.swing.JFrame {

    public ResultSet rs;
   public Statement st;
   public Connection con;
    private PreparedStatement pst;
    int amount, select_table_total, budget_num, main_budget;
    String Sessions;
    String khat_pur;
    String table_Click, table_Click1, table_Click2, table_Click3, table_Click4, table_Click5;
    int ID;
    /**
     * Creates new form Non_govt_purchase
     */
    public Non_govt_purchase() {
        initComponents();
        Connection();
        khat_and_session_show();
        setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public void Connection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/budget_of_polytechnic", "root", "");

            st = con.createStatement();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
    
    public void khat_and_session_show()
    {
        try
        {
            String sql = "select distinct session from non_govt_main";
            rs = st.executeQuery(sql);
            while (rs.next()) {
                String pat = rs.getString("session");
                session_com.addItem(pat.trim());
            }
            
            String sql1 = "select Khat from non_govt";
            rs = st.executeQuery(sql1);
            while (rs.next()) {
                String pat1 = rs.getString("Khat");
                khat_conbo.addItem(pat1.trim());
                Khat_pur_details.addItem(pat1.trim());
                khat_pur="";
            }
            
            String sql2 = "select distinct session from non_govt_purchase";
            rs = st.executeQuery(sql2);
            while (rs.next()) {
                String pat1 = rs.getString("session");
                Session_pur_details.addItem(pat1.trim());
                Sessions="";
            }
            
           
        
        }
        catch (Exception e) 
           {
                JOptionPane.showMessageDialog(rootPane, "Database Error");
           }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        khat_conbo = new javax.swing.JComboBox<>();
        pur_date = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Description = new javax.swing.JTextField();
        bill = new javax.swing.JTextField();
        vat = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        it = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        session_com = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Session_pur_details = new javax.swing.JComboBox<>();
        Date_pur_details = new com.toedter.calendar.JDateChooser();
        Khat_pur_details = new javax.swing.JComboBox<>();
        showResults = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        purchase = new javax.swing.JButton();
        update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        showAll = new javax.swing.JButton();
        govt_pur = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Purchase_details_table = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        total_bill = new javax.swing.JLabel();
        total_vat = new javax.swing.JLabel();
        total_it = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        remaining = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Non Govt. Purchase");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Date");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Khat");

        khat_conbo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        pur_date.setDateFormatString("yyyy-MM-dd");
        pur_date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Description");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Bill");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Vat");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("IT");

        Description.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        bill.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        vat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("%");

        it.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("%");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Session");

        session_com.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Purchase Details");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Session");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Date");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Khat");

        Session_pur_details.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Session_pur_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Session_pur_detailsActionPerformed(evt);
            }
        });

        Date_pur_details.setDateFormatString("yyyy-MM-dd");
        Date_pur_details.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        Khat_pur_details.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Khat_pur_details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Khat_pur_detailsActionPerformed(evt);
            }
        });

        showResults.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showResults.setText("Show Results");
        showResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showResultsActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("TO");

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Session_pur_details, 0, 171, Short.MAX_VALUE)
                                .addComponent(Khat_pur_details, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Date_pur_details, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(showResults)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Session_pur_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(Date_pur_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(Khat_pur_details, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(showResults))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        purchase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        purchase.setText("Purchase");
        purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        Delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Log Out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        showAll.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        showAll.setText("Show All");
        showAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllActionPerformed(evt);
            }
        });

        govt_pur.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        govt_pur.setText("Govt. Purchase");
        govt_pur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                govt_purActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(govt_pur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(purchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(purchase)
                .addGap(18, 18, 18)
                .addComponent(showAll)
                .addGap(18, 18, 18)
                .addComponent(update)
                .addGap(18, 18, 18)
                .addComponent(Delete)
                .addGap(18, 18, 18)
                .addComponent(govt_pur)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(khat_conbo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(vat, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(it, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pur_date, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(session_com, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pur_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(session_com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(khat_conbo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(it, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Purchase_details_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Khat", "Session", "Date", "Descriptions", "Bill", "Vat", "IT", "Total_Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Purchase_details_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Purchase_details_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Purchase_details_table);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Total Bill");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Total VAT");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Total IT");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Total ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Remaining");

        total_bill.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        total_bill.setText("0");

        total_vat.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        total_vat.setText("0");

        total_it.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        total_it.setText("0");

        total.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        total.setText("0");

        remaining.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        remaining.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 987, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel17))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(7, 7, 7)
                                            .addComponent(jLabel16))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(total_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_vat, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total_it, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(remaining, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(total_bill))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(total_vat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(total_it))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(total))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(remaining))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void purchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseActionPerformed
        String Purchase_date = ((JTextField) pur_date.getDateEditor().getUiComponent()).getText();
        String khat = khat_conbo.getSelectedItem().toString();
        String sessions = session_com.getSelectedItem().toString();
        String Descriptions = Description.getText();
        int Bill = Integer.parseInt(bill.getText());
        int Vat = (Bill*Integer.parseInt(vat.getText()))/100;
        int IT = (Bill*Integer.parseInt(it.getText()))/100;
        String n = null;
        int Total_cost = Bill + Vat + IT;
        
         try{

           String sql2 = "select * from non_govt where Khat = '" + khat + "' ";
            rs = st.executeQuery(sql2);
            while (rs.next()) {
                
                String bud = rs.getString("Total_Amount");
                amount = Integer.parseInt(bud);
                System.out.println(" "+amount);
            }

                if ( amount < Total_cost)
                {
                    JOptionPane.showMessageDialog(rootPane, "Insufficient balance");
                }
                else
                {
                    String sql1 = "insert into non_govt_purchase(Khat, session, date, Description, Bill, Vat, IT, Total_Amount ) values ('" + khat + "','" + sessions + "','" + Purchase_date + "','" + Descriptions + "','" + Bill + "','" + Vat + "','" + IT + "','" + Total_cost + "')";
                    pst = con.prepareStatement(sql1);
                    pst.execute();
                    System.out.println("YES");
                    int update_value = amount - Total_cost;
                    
                    String sql3 = "UPDATE non_govt SET Total_Amount='" + update_value + "' WHERE Khat='" + khat + "' ";
                    pst = con.prepareStatement(sql3);
                    pst.execute();
                    
                }
            }
                catch(Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Database Error");
                }
    }//GEN-LAST:event_purchaseActionPerformed

    private void showResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showResultsActionPerformed

        String Date_one_pur = ((JTextField) Date_pur_details.getDateEditor().getUiComponent()).getText();
        String Date_two_pur = ((JTextField) jDateChooser1.getDateEditor().getUiComponent()).getText();
        
        if(Date_one_pur.equals("") && Date_two_pur.equals("") && khat_pur.equals(""))
        {
            System.out.println(" "+Sessions+"  "+khat_pur+"  "+Date_one_pur+"  "+Date_two_pur);
             try{
                String sql1 = "SELECT * FROM non_govt_purchase WHERE session = '" + Sessions + "' ";
                pst = con.prepareStatement(sql1);
                rs = pst.executeQuery();
                Purchase_details_table.setModel(DbUtils.resultSetToTableModel(rs));
                Purchase_details_table.getColumnModel().getColumn(0).setPreferredWidth(70);
                Purchase_details_table.getColumnModel().getColumn(1).setPreferredWidth(150);
                Purchase_details_table.getColumnModel().getColumn(2).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(3).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(4).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(5).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(6).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(7).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(8).setPreferredWidth(80);
                Sessions="";
                int RowCount = Purchase_details_table.getRowCount();
                int sum = 0, sum1= 0, sum2= 0,sum3= 0;
                for (int i = 0; i < RowCount; i++) {
                    sum = sum + Integer.parseInt(Purchase_details_table.getValueAt(i, 5).toString());
                    sum1 = sum1 + Integer.parseInt(Purchase_details_table.getValueAt(i, 6).toString());
                    sum2 = sum2 + Integer.parseInt(Purchase_details_table.getValueAt(i, 7).toString());
                    sum3 = sum3+ Integer.parseInt(Purchase_details_table.getValueAt(i, 8).toString());
                }
                total_bill.setText(String.valueOf(sum));
                total_vat.setText(String.valueOf(sum1));
                total_it.setText(String.valueOf(sum2));
                total.setText(String.valueOf(sum3));
        }
       catch(Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Database Error");
                }
        
        }
        
        else if(Sessions.equals("") && khat_pur.equals(""))
        {
            System.out.println(" "+Sessions+"  "+khat_pur+"  "+Date_one_pur+"  "+Date_two_pur);
             try{
                String sql1 = "SELECT * FROM non_govt_purchase WHERE date >= '" + Date_one_pur + "' AND date <= '" + Date_two_pur + "'";
                pst = con.prepareStatement(sql1);
                rs = pst.executeQuery();
                Purchase_details_table.setModel(DbUtils.resultSetToTableModel(rs));
                Purchase_details_table.getColumnModel().getColumn(0).setPreferredWidth(70);
                Purchase_details_table.getColumnModel().getColumn(1).setPreferredWidth(150);
                Purchase_details_table.getColumnModel().getColumn(2).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(3).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(4).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(5).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(6).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(7).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(8).setPreferredWidth(80);
               
                
               int RowCount = Purchase_details_table.getRowCount();
                int sum = 0, sum1= 0, sum2= 0,sum3= 0;
                for (int i = 0; i < RowCount; i++) {
                   sum = sum + Integer.parseInt(Purchase_details_table.getValueAt(i, 5).toString());
                    sum1 = sum1 + Integer.parseInt(Purchase_details_table.getValueAt(i, 6).toString());
                    sum2 = sum2 + Integer.parseInt(Purchase_details_table.getValueAt(i, 7).toString());
                    sum3 = sum3+ Integer.parseInt(Purchase_details_table.getValueAt(i, 8).toString());
                }
                total_bill.setText(String.valueOf(sum));
                total_vat.setText(String.valueOf(sum1));
                total_it.setText(String.valueOf(sum2));
                total.setText(String.valueOf(sum3));
        }
       catch(Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Database Error");
                }
        
        }
        
        else if(Sessions.equals("") && Date_one_pur.equals("") && Date_two_pur.equals(""))
        {
            System.out.println(" "+Sessions+"  "+khat_pur+"  "+Date_one_pur+"  "+Date_two_pur);
             try{
                String sql1 = "SELECT * FROM non_govt_purchase WHERE  Khat = '" + khat_pur + "'";
                pst = con.prepareStatement(sql1);
                rs = pst.executeQuery();
                Purchase_details_table.setModel(DbUtils.resultSetToTableModel(rs));
                Purchase_details_table.getColumnModel().getColumn(0).setPreferredWidth(70);
                Purchase_details_table.getColumnModel().getColumn(1).setPreferredWidth(150);
                Purchase_details_table.getColumnModel().getColumn(2).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(3).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(4).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(5).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(6).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(7).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(8).setPreferredWidth(80);
               
                khat_pur="";
               int RowCount = Purchase_details_table.getRowCount();
                int sum = 0, sum1= 0, sum2= 0,sum3= 0;
                for (int i = 0; i < RowCount; i++) {
                    sum = sum + Integer.parseInt(Purchase_details_table.getValueAt(i, 5).toString());
                    sum1 = sum1 + Integer.parseInt(Purchase_details_table.getValueAt(i, 6).toString());
                    sum2 = sum2 + Integer.parseInt(Purchase_details_table.getValueAt(i, 7).toString());
                    sum3 = sum3+ Integer.parseInt(Purchase_details_table.getValueAt(i, 8).toString());
                }
                total_bill.setText(String.valueOf(sum));
                total_vat.setText(String.valueOf(sum1));
                total_it.setText(String.valueOf(sum2));
                total.setText(String.valueOf(sum3));
        }
       catch(Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Database Error");
                }
        
        }

    }//GEN-LAST:event_showResultsActionPerformed

    private void Session_pur_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Session_pur_detailsActionPerformed
         Sessions = Session_pur_details.getSelectedItem().toString();
    }//GEN-LAST:event_Session_pur_detailsActionPerformed

    private void Khat_pur_detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Khat_pur_detailsActionPerformed
        khat_pur = Khat_pur_details.getSelectedItem().toString();
    }//GEN-LAST:event_Khat_pur_detailsActionPerformed

    private void showAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllActionPerformed
        try{
                String sql1 = "SELECT * FROM non_govt_purchase";
                pst = con.prepareStatement(sql1);
                rs = pst.executeQuery();
                Purchase_details_table.setModel(DbUtils.resultSetToTableModel(rs));
                Purchase_details_table.getColumnModel().getColumn(0).setPreferredWidth(70);
                Purchase_details_table.getColumnModel().getColumn(1).setPreferredWidth(150);
                Purchase_details_table.getColumnModel().getColumn(2).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(3).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(4).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(5).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(6).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(7).setPreferredWidth(80);
                Purchase_details_table.getColumnModel().getColumn(8).setPreferredWidth(80);
                
               
              int RowCount = Purchase_details_table.getRowCount();
                int sum = 0, sum1= 0, sum2= 0,sum3= 0;
                for (int i = 0; i < RowCount; i++) {
                    sum = sum + Integer.parseInt(Purchase_details_table.getValueAt(i, 5).toString());
                    sum1 = sum1 + Integer.parseInt(Purchase_details_table.getValueAt(i, 6).toString());
                    sum2 = sum2 + Integer.parseInt(Purchase_details_table.getValueAt(i, 7).toString());
                    sum3 = sum3+ Integer.parseInt(Purchase_details_table.getValueAt(i, 8).toString());
                }
                total_bill.setText(String.valueOf(sum));
                total_vat.setText(String.valueOf(sum1));
                total_it.setText(String.valueOf(sum2));
                total.setText(String.valueOf(sum3));
        }
       catch(Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Database Error");
                }
    }//GEN-LAST:event_showAllActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
         int r = JOptionPane.showConfirmDialog(null, "Do you really want to delete", "Delete", JOptionPane.YES_NO_OPTION);
        if (r == 0) {
            try {
                String sql2 = "select Total_Amount from non_govt Where Khat='" + table_Click5 + "'";
                 rs = st.executeQuery(sql2);
                if(rs.next())
                {
                    String num = rs.getString("Total_Amount");
                    budget_num =Integer.parseInt(num);
                }
                
                String sql = "delete from non_govt_purchase Where ID='" + ID + "'";
                pst = con.prepareStatement(sql);
                pst.execute();
                DefaultTableModel model = (DefaultTableModel) Purchase_details_table.getModel();
                model.removeRow(Purchase_details_table.getSelectedRow());
                
                int update_value = budget_num+ select_table_total;
                String sql1 = "UPDATE non_govt SET Total_Amount='" + update_value + "'  where Khat='" + table_Click5 + "'";
                pst = con.prepareStatement(sql1);
                pst.execute();
               

            } catch (Exception ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void Purchase_details_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Purchase_details_tableMouseClicked
        try {
            int row = Purchase_details_table.getSelectedRow();
            
            table_Click = (Purchase_details_table.getModel().getValueAt(row, 5).toString());
            table_Click1 = (Purchase_details_table.getModel().getValueAt(row, 6).toString());
            table_Click2 = (Purchase_details_table.getModel().getValueAt(row, 7).toString());
            table_Click3 = (Purchase_details_table.getModel().getValueAt(row, 8).toString());
           
            table_Click4 = (Purchase_details_table.getModel().getValueAt(row, 0).toString());
            table_Click5 = (Purchase_details_table.getModel().getValueAt(row, 1).toString());
            ID = Integer.parseInt(table_Click4);
            select_table_total= Integer.parseInt(table_Click3);
            bill.setText(table_Click);
            vat.setText(table_Click1);
            it.setText(table_Click2);
            
        } catch (Exception e) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_Purchase_details_tableMouseClicked

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        int B = Integer.parseInt(bill.getText());
        int V = (B*Integer.parseInt(vat.getText()))/100;
        int I = (B*Integer.parseInt(it.getText()))/100;
        
        int T = B+V+I;
        System.out.println("  "+select_table_total + "  "+T );
        int q = JOptionPane.showConfirmDialog(null, "Do you really want to update", "Update", JOptionPane.YES_NO_OPTION);
         if (q == 0) {
            try {
               String sql2 = "select * from non_govt where Khat = '" + table_Click5 + "' ";
                rs = st.executeQuery(sql2);
                while (rs.next()) {
                
                    String bud = rs.getString("Total_Amount");
                    main_budget = Integer.parseInt(bud);
                }
                  
                if (select_table_total <= T)
                {
                    int prv_budget = T - select_table_total;
                    int new_budget = main_budget-prv_budget;
                    String sql6 = "UPDATE non_govt SET Total_Amount='" + new_budget + "'  WHERE Khat='" + table_Click5 + "'";
                    pst = con.prepareStatement(sql6);
                    pst.execute();
                }
                else if(select_table_total > T)
                { 
                    int num1 = select_table_total- T;
                    int num2 = main_budget + num1;
                    String sql7 = "UPDATE non_govt SET Total_Amount='" + num2 + "'  WHERE CODE='" + table_Click5 + "'";
                    pst = con.prepareStatement(sql7);
                    pst.execute();
                
                }
                String sql8 = "UPDATE non_govt_purchase SET Bill='" + B + "'  ,Vat='" + V + "',IT='" + I + "',Total_Amount='" + T + "'  WHERE ID='" + ID + "'";
                pst = con.prepareStatement(sql8);
                pst.execute();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Database Error");
            }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void govt_purActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_govt_purActionPerformed
        Purchase p = new Purchase();
        p.show();
        this.dispose();
    }//GEN-LAST:event_govt_purActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Login l = new Login();
        l.show();
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Non_govt_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Non_govt_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Non_govt_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Non_govt_purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Non_govt_purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Date_pur_details;
    private javax.swing.JButton Delete;
    private javax.swing.JTextField Description;
    private javax.swing.JComboBox<String> Khat_pur_details;
    private javax.swing.JTable Purchase_details_table;
    private javax.swing.JComboBox<String> Session_pur_details;
    private javax.swing.JTextField bill;
    private javax.swing.JButton govt_pur;
    private javax.swing.JTextField it;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> khat_conbo;
    private com.toedter.calendar.JDateChooser pur_date;
    private javax.swing.JButton purchase;
    private javax.swing.JLabel remaining;
    private javax.swing.JComboBox<String> session_com;
    private javax.swing.JButton showAll;
    private javax.swing.JButton showResults;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total_bill;
    private javax.swing.JLabel total_it;
    private javax.swing.JLabel total_vat;
    private javax.swing.JButton update;
    private javax.swing.JTextField vat;
    // End of variables declaration//GEN-END:variables
}
